---
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: add elasticsearch repository key
  become: true
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: add elasticsearch repository
  apt_repository:
    repo: "{{ es_apt_url }}"
    filename: "elastic-{{ es_version.split('.')[0] }}.x"
    state: present

- name: install elasticsearch
  become: true
  apt:
    name: elasticsearch={{ es_version }}
    state: present
  register: _es_install
  notify: restart elasticsearch
