---
- name: ensure supported version
  assert:
    that: es_version is not none and es_version | string is match("^[567]\.\d+\.\d+")
    msg: es_version major version must be 5, 6, or 7 and full version must be specified

- name: include os-specific vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: include installation tasks ({{ ansible_os_family | lower }})
  include: "install-{{ ansible_os_family | lower }}.yml"

- name: include configuration tasks
  include: configure.yml

- name: include plugin tasks
  include: plugins.yml

- include_tasks: curator.yml
  when: es_install_curator | bool

- name: manage service
  service:
    name: elasticsearch
    state: "{{ es_start_service | ternary('started', 'stopped') }}"
    enabled: "{{ es_enable_service }}"
