---
- assert:
    that: es_version is not none and es_version | string | match("^[56]\.\d+\.\d+")
    msg: es_version major version must be 5 or 6 and full version must be specified

- name: include os-specific vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: manage service group
  group:
    state: present
    name: elasticsearch
    system: yes
    gid: "{{ es_group_id }}"
  notify: restart elasticsearch
  when: es_user_id is not none and us_group_id is not none

- name: manage service user
  user:
    state: present
    name: elasticsearch
    comment: elasticsearch system user
    system: yes
    createhome: no
    uid: "{{ es_user_id }}"
    group: elasticsearch
  notify: restart elasticsearch
  when: es_user_id is not none and us_group_id is not none

- name: include installation tasks ({{ ansible_os_family | lower }})
  include: "install-{{ ansible_os_family | lower }}.yml"

- name: include configuration tasks
  include: configure.yml

- name: include plugin tasks
  include: plugins.yml

- name: manage service
  service:
    name: elasticsearch
    state: "{{ es_service_enabled | bool | ternary('started', 'stopped') }}"
    enabled: "{{ es_service_enabled }}"
