---
- name: determine if plugin reinstall is necessary
  set_fact:
    es_plugins_reinstall: true
  when: _es_install is defined and _es_install.changed
  tags: ["skip_ansible_lint"]

- name: list installed plugins
  command: "ls /usr/share/elasticsearch/plugins"
  register: _es_installed_plugins
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: determine plugins to remove/install (not during re-install)
  set_fact:
    # remove plugins installed but not listed in es_plugins
    _es_plugins_to_remove: "{{ _es_installed_plugins.stdout_lines | difference(es_plugins | json_query('[*].plugin')) | default([]) }}"
    # install plugins listed in es_plugins not already installed
    _es_plugins_to_install: "{{ es_plugins | json_query('[*].plugin') | difference(_es_installed_plugins.stdout_lines) | default([]) }}"
  when: not es_plugins_reinstall

- name: determine plugins to remove/install (during re-install)
  set_fact:
    # remove all found on system
    _es_plugins_to_remove: "{{ _es_installed_plugins.stdout_lines | default([]) }}"
    # add all listed in es_plugins
    _es_plugins_to_install: "{{ es_plugins | json_query('[*].plugin') | default([]) }}"
  when: es_plugins_reinstall | bool

- name: remove elasticsearch plugins
  command: "{{ es_home }}/bin/elasticsearch-plugin remove {{ item }} --silent"
  ignore_errors: true
  with_items: "{{ _es_plugins_to_remove }}"
  when: _es_plugins_to_remove | length
  environment:
    CONF_DIR: "{{ es_conf_dir }}"
    ES_PATH_CONF: "{{ es_conf_dir }}"
    ES_INCLUDE: "{{ es_environment_file }}"
  notify: restart elasticsearch

- name: install elasticsearch plugins
  command: "{{ es_home }}/bin/elasticsearch-plugin install {{ item.url | default(item.plugin) }} --batch --silent"
  when: item.plugin in _es_plugins_to_install
  with_items: "{{ es_plugins }}"
  register: _es_plugin_installed
  changed_when: _es_plugin_installed.rc == 0
  notify: restart elasticsearch
  environment:
    CONF_DIR: "{{ es_conf_dir }}"
    ES_PATH_CONF: "{{ es_conf_dir }}"
    ES_INCLUDE: "{{ es_environment_file }}"
  until: _es_plugin_installed.rc == 0
  retries: 5
  delay: 5
