---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when:
    - es_restart_on_change
    - es_enable_service
    - es_start_service
